In [2]:
import numpy as np


array_1_to_10 = np.arange(1, 11)


reshaped_array = array_1_to_10.reshape(2, 5)
print("Reshaped Array (2x5):\n", reshaped_array)


Reshaped Array (2x5):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:

array_1_to_20 = np.arange(1, 21)


extracted_elements = array_1_to_20[5:15]
print("Elements between the 5th and 15th index:\n", extracted_elements)


Elements between the 5th and 15th index:
 [ 6  7  8  9 10 11 12 13 14 15]


In [6]:
import pandas as pd


fruit_series = pd.Series({'apples': 3, 'bananas': 2, 'oranges': 1})


fruit_series['pears'] = 4
print("Updated Fruit Series:\n", fruit_series)


Updated Fruit Series:
 apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [8]:

data = {
    'name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah', 'Ivy', 'Jack'],
    'age': [28, 34, 22, 45, 29, 37, 30, 32, 24, 40],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'F', 'M']
}
df = pd.DataFrame(data)
print("Dataframe:\n", df)


Dataframe:
       name  age gender
0    Alice   28      F
1      Bob   34      M
2  Charlie   22      M
3    David   45      M
4      Eva   29      F
5    Frank   37      M
6    Grace   30      F
7   Hannah   32      F
8      Ivy   24      F
9     Jack   40      M


In [10]:

df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
print("Dataframe with Occupation:\n", df)


Dataframe with Occupation:
       name  age gender  occupation
0    Alice   28      F  Programmer
1      Bob   34      M     Manager
2  Charlie   22      M     Analyst
3    David   45      M  Programmer
4      Eva   29      F     Manager
5    Frank   37      M     Analyst
6    Grace   30      F  Programmer
7   Hannah   32      F     Manager
8      Ivy   24      F     Analyst
9     Jack   40      M  Programmer


In [12]:

filtered_df = df[df['age'] >= 30]
print("Rows where age is greater than or equal to 30:\n", filtered_df)


Rows where age is greater than or equal to 30:
      name  age gender  occupation
1     Bob   34      M     Manager
3   David   45      M  Programmer
5   Frank   37      M     Analyst
6   Grace   30      F  Programmer
7  Hannah   32      F     Manager
9    Jack   40      M  Programmer


In [14]:

df.to_csv('dataframe.csv', index=False)


read_df = pd.read_csv('dataframe.csv')
print("Contents of the CSV file:\n", read_df)


Contents of the CSV file:
       name  age gender  occupation
0    Alice   28      F  Programmer
1      Bob   34      M     Manager
2  Charlie   22      M     Analyst
3    David   45      M  Programmer
4      Eva   29      F     Manager
5    Frank   37      M     Analyst
6    Grace   30      F  Programmer
7   Hannah   32      F     Manager
8      Ivy   24      F     Analyst
9     Jack   40      M  Programmer
